<a href="https://colab.research.google.com/github/MarioCid90/EJERCICIOS-DE-INICIACION-A-PYTHON/blob/main/Ejercicios_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
#1- Crea un array con 4 vectores de 3 números aleatorios del 0 al 1
np.random.rand(4,3)


array([[0.04802223, 0.84001278, 0.33408703],
       [0.48971875, 0.38963342, 0.20567753],
       [0.39845362, 0.45106456, 0.08770577],
       [0.12123969, 0.37762936, 0.08365099]])

In [ ]:
#2- Crea un array de valores ordenados del 0 al 4
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
#3-Crea un array de valores del 2 al 15
np.arange(2,16)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
#4- crea un array de 20 valores lineales entre 0 y 1

np.linspace(0,1,20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#5- Crea una variable de un array de 25 cifras solo con números enteros que vaya del 0 al 17

a=np.linspace(0, 17 ,25, dtype=int)

In [ ]:
#6- Ordena de manera inversa el array creado en el ejercicio 6 con .sort

np.sort(a)[::-1]

array([17, 16, 15, 14, 14, 13, 12, 12, 11, 10,  9,  9,  8,  7,  7,  6,  5,
        4,  4,  3,  2,  2,  1,  0,  0])

In [ ]:
#7- Crea una variable con un array de dos vectores y 3 cifras con números enteros aleatorios
a=np.random.randint(10, size=(2,3))
a

array([[8, 6, 0],
       [0, 4, 2]])

In [ ]:
#-8-Muestra el array anterior ordenado por filas
np.sort(a, axis=0)


array([[0, 4, 0],
       [8, 6, 2]])

In [ ]:
#9-Muestra el array anterior ordenado por columnas
np.sort(a, axis=1)


array([[0, 6, 8],
       [0, 2, 4]])

In [ ]:
#10-Muestra el array anterior ordenado por filas de manera descendente
np.sort(a, axis=1)[::-1]

array([[0, 2, 4],
       [0, 6, 8]])

In [ ]:
#11-Crea dos array de un solo vector y 6 cifras cada uno y concaténalos en un solo vector

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#12-crea dos arrays con dos vectores cada uno y concatenalos
# en una sola matriz dividiendolos por filas
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

np.concatenate((a,b))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#13- Misma operación que en el 12 pero ordenado por columnas
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#14- Elimina la tercera columna del resultado del ejercicio anterior
np.delete(np.concatenate((a,b), axis=1),2, axis=1)


array([[1, 2, 6],
       [3, 4, 8]])

In [ ]:
#15-Crea un array de 3 cifras y añadele 2 cifras extra
a=np.array([1,2,3])
np.append(a, [4,5])



array([1, 2, 3, 4, 5])

In [ ]:
#16- Crea una matriz bidimensional, después le añades un vector más
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.append(a, [[10,11,12]], axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#17- Crea un array 5 cifras, después le añades el número 33 en la posición 4
a=np.array([1,2,3,4,5])
np.insert(a,4,33)

array([ 1,  2,  3,  4, 33,  5])

In [ ]:
#18- Crea un array bidimensional e incluye el número 0 en la posición 1 de cada vector
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.insert(a,1,0, axis=1)

array([[1, 0, 2, 3],
       [4, 0, 5, 6],
       [7, 0, 8, 9]])

19- Usa las funciones específicas para:

In [ ]:
#A- Mostrar número de dimensiones del anterior array
a.ndim

2

In [ ]:
#B- mostrar número de elementos del anterior array
a.size

9

In [ ]:
#C- Mostrar una tupla con las dimensiones del anterior array
a.shape

(3, 3)

In [ ]:
#20- Crea una matriz de 9 elementos ordenados del 0 al 8
a=np.arange(9)

In [ ]:
#21- Crea una matriz con 3 vectores usando la matriz anterior
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#22- Crea un array de 3 matrices con 3 vectores y 3 elementos cada una

a=np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#23- Muestra los el elemento 1 del vector 2 de cada una de las matrices
a[:,1,1]

array([ 4, 13, 22])

In [ ]:
#24- Muestrame el tercer elemento de cada vector
a[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [3]:
#25- Crea dos matrices de 4 submatrices 3 vectores cada matriz y 4 cifras cada matriz
data=np.arange(0, 96).reshape(2,4,3,4)
data


array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]],


       [[[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71]],

        [[72, 73, 74, 75],
         [76, 77, 78, 79],
         [80, 81, 82, 83]],

        [[84, 85, 86, 87],
         [88, 89, 90, 91],
         [92, 93, 94, 95]]]])

In [4]:
#26- Del anterior array muéstrame los números 50 y 70
data[1, [0,1], [0,2], 2]

array([50, 70])

In [5]:
#27- Del mismo array muéstrame 48, 50, 68, 70
data[1,[0,0,1,1],[0,0,2,2],[0,2,0,2]]

array([48, 50, 68, 70])

28- Crea un array que sea una matriz con 4 vectores y 4 cifras por vector y realiza las siguientes operaciones

In [6]:
#A-Crea el Array e indica con booleanos cuales son menores de 5 y cuales no
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [9]:
#B-Muestra los valores menores de 5
a[a<5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [10]:
#C- Muestra los números pares
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [12]:
#D- Muestra números impares y mayores que 7
a[(a%2!=0) & (a>7)]


array([ 9, 11])

In [14]:
#E- Muestra los números pares o que sean menores de 6
a[(a%2==0) | (a<6)]


array([ 1,  2,  3,  4,  5,  6,  8, 10, 12])

29- Crea dos array que se compongan de una matriz de dos vectores con 2 cifras cada uno y realiza las siguientes operaciones

In [15]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [16]:
#A-Concatena ambos array verticalemte (por filas)
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
#B-Concatenalos ahora de manera horizontal (por columnas)
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

30- Crea un array de 48 cifras en orden de 1 al 48 y realiza las siguientes operaciones:

In [18]:
a=np.arange(1,49)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [23]:
#A-Con el anterior array crea 4 vectores de 12 cifras cada uno
x=a.reshape(4,12)
x


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [26]:
#B- Ahora con 'x' crea 4 matrices de 4 vectores cada una
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [25, 26, 27, 28],
        [37, 38, 39, 40]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20],
        [29, 30, 31, 32],
        [41, 42, 43, 44]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [33, 34, 35, 36],
        [45, 46, 47, 48]])]

In [28]:
#C-Y por último con 'x' saca el vector 1 completo
np.vsplit(x,4)[1]



array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])